# Generated by Django 4.2.12 on 2026-03-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_id',
        ),
    ]
