# Generated by Django 4.2.12 on 2026-03-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
